version: '3'

services:
  scheduler:
    image: backend
    build: .
#    command: air --build.cmd "go build -o bin/scheduler src/scheduler/main.go" --build.bin "./bin/scheduler"
    command: ./bin/scheduler
    environment:
      BROKER_URL: kafka:9092
      TOPICS: "scheduled1,scheduled2"
    volumes:
      - ./src/:/app/src/

  producer:
    scale: 10
    build: .
#    command: air --build.cmd "go build -o bin/producer src/producer/main.go" --build.bin "./bin/producer"
    command: ./bin/producer
    environment:
      BROKER_URL: kafka:9092
      TOPICS: "scheduled1,scheduled2"
    volumes:
      - ./src/:/app/src/

  consumer:
    build: .
#    command: air --build.cmd "go build -o bin/consumer src/consumer/main.go" --build.bin "./bin/consumer"
    command: ./bin/consumer
    restart: on-failure
    environment:
      BROKER_URL: kafka:9092
      TOPICS: "scheduled1,scheduled2"
    volumes:
      - ./src/:/app/src/

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPIC: "scheduled1,scheduled2"
